---
title: "Preprocessing"
author: "Mbouamboua Yvon<BR>mbouamboua@ipmc.cnrs.fr"
output:
  html_notebook:
    fig_caption: yes
    toc: yes
    toc_depth: 3
    toc_float: yes
date: 'Last update: `r format(Sys.time())`'
---

# Defining working directory and subfolders

```{r setup}

dir.main = "/data/data_mbouamboua/projects/human_olfactory_cf"
dir.data = file.path(dir.main, "data")
h5.mtx <- "filtered_feature_bc_matrix.h5"
file.name <- list("G3_M2_M9","G1_M7_M10","M1_M5_M6","D571_572_573","D574_575_576_577")
dir.results <- file.path(dir.main, paste0("000-preprocessing"))
result.folders <- list("rdata","seurat_data", "tables", "plots", "markers","markers_durante")

dir.path <- c()
for (folder in result.folders) {
  dir.path[folder] <- file.path(dir.results, folder)
  if(!dir.exists(dir.path[folder])){
   dir.create(dir.path[folder], showWarnings = FALSE, recursive = TRUE) 
  }
}

```

# Load R packages and helper functions

```{r package_function}

suppressPackageStartupMessages({
  library(Seurat)
  library(SeuratDisk)
  library(ggplot2)
  library(dplyr)
  library(pheatmap)
  library(ComplexHeatmap)
  library(ComplexUpset)
  library(stringr)
  library(patchwork)
})

source(file.path("/data/data_mbouamboua/utils/00-import.R"))

```
